### PR TITLE
Draft: Split ASMPatches

### PR DESCRIPTION
**Pull request by namishere**
This moves the contents of ASMPatches into individual cpp files for better organization. This also moves ASM patches that were in LuaInterface cpp files into said files, as well as attempting to clean up headers on the ASM side.

### CODE REVIEW

**Comment by namishere** [comment]
i've not had any issues with this, but this is a big enough change that i think there should be a couple extra sets of eyes looking over it before merging

**Comment by Sylmir** [comment]
Have you taken the time to check each patch ingame individually ?

**Comment by namishere** [comment]
given the number of them, no. i have specifically tested a couple i felt could be problematic (Fire[Boss]ProjectilesEx, CheckFamiliarsEx), and gone through some runs with x32dbg hooked

**Comment by Sylmir** [comment]
- [ ] LogMessage
- [ ] AmbushWaveCount
- [ ] MegaSatanEnding
- [ ] ConsoleRunCommand
- [ ] BlueWombCurse
- [ ] ModsMenu
  - [ ] MenuFont 1
  - [ ] MenuFont 2
- [ ] FireProjectiles
- [ ] FireBossProjectiles
- [ ] glDrawElements
- [ ] PreSampleLaserCollision
- [ ] PreLaserCollision
- [ ] PreEntityTakeDamage
  - [ ] Entity
  - [ ] Player
- [ ] PostEntityTakeDamage
  - [ ] Entity
  - [ ] Player
- [ ] FamiliarCustomTags
  - [ ] DamagedByLaser
  - [ ] DamagedByProjectiles
  - [ ] GetMultiplier
- [ ] CheckFamiliar
- [ ] VoidGeneration
- [ ] HushBug
  - [ ] Patch1
  - [ ] Patch2
- [ ] NullItem / NullCostume
- [ ] PrePlayerUseBomb
- [ ] PostPlayerUseBomb
- [ ] PreMMorphActiveCallback
- [ ] MenuOptionsLanguageChange
- [ ] TrySplit
- [ ] GridCallback
  - [ ] RoomSpawnEntity
  - [ ] PostSpawnGridEntity
    - [ ] Patch1
    - [ ] Patch2
  - [ ] InlinedSpawnGridEntity (19 patches, not checking them individually)
- [ ] InputAction
- [ ] PlayerStats
  - [ ] FireDelay
  - [ ] Speed
  - [ ] Damage
  - [ ] Range
  - [ ] ShotSpeed
  - [ ] Luck
- [ ] SpawnSpecialQuestDoor
- [ ] PostNightmareScene
- [ ] delirium::Transformation
- [ ] delirium::PostTransformation

**Review by ConnorForan — APPROVED** [review]
Tested some stuff I'm familiar with (Laser/TakeDamage/etc) and noticed no issues. Overall the change looks fine to me, just quickly test some of the remaining stuff like grids/stats

**Pull request merged**
